[package]
name = "converge-executor"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description.workspace = true
publish.workspace = true

[dependencies]
atomic-write-file.workspace = true
converge-core = { version = "=0.1.0", path = "../converge-core" }
converge-discovery = { version = "=0.1.0", path = "../converge-discovery" }
converge-model = { version = "=0.1.0", path = "../converge-model" }
fs2.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true

[dev-dependencies]
converge-planner = { version = "=0.1.0", path = "../converge-planner" }
tempfile.workspace = true
walkdir.workspace = true

[lints]
workspace = true
